CREATE TABLE fruites (NAME VARCHAR(20));
INSERT INTO fruites (NAME) VALUES ('Apple');
INSERT INTO fruites (NAME) VALUES ('Orange');
INSERT INTO fruites (NAME) VALUES ('Banana');
INSERT INTO fruites (NAME) VALUES ('Rasberry');
CREATE TABLE vegetables (NAME VARCHAR(20));
INSERT INTO vegetables (NAME) VALUES ('Carrot');
INSERT INTO vegetables (NAME) VALUES ('Potato');
INSERT INTO vegetables (NAME) VALUES ('Spinach');
INSERT INTO vegetables (NAME) VALUES ('Broccoli');
INSERT INTO vegetables (NAME) VALUES ('Tomato');
CREATE TABLE passwords (NAME VARCHAR(20));
INSERT INTO passwords (NAME) VALUES ('123');
INSERT INTO passwords (NAME) VALUES ('123456');
INSERT INTO passwords (NAME) VALUES ('abc');
INSERT INTO passwords (NAME) VALUES ('abcd');
CREATE TABLE secrets (NAME VARCHAR(20));
INSERT INTO secrets (NAME) VALUES ('a');
INSERT INTO secrets (NAME) VALUES ('b');
INSERT INTO secrets (NAME) VALUES ('c');
