name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Install PG dump
        run: apt-get -y install postgresql-client-15
      - name: Check pg_dump version
        run: pg_dump --version
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          cache-dependency-path: server/pom.xml
      - working-directory: client
        run: npm ci
      - working-directory: client
        run: npm run build
      - working-directory: server
        run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt

      - run: python scripts/build_docker_image.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}
