name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mucsi96/postgres-backup-tool-devcontainer
          cacheFrom: ghcr.io/mucsi96/postgres-backup-tool-devcontainer
          push: always
          runCmd: |
            cd client npm ci
            npm run build
            cd ../server mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt

      - run: python scripts/build_docker_image.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}
