name: Test

on:
  pull_request:
    branches: [main]

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
      - working-directory: client
        run: npm ci
      - working-directory: client
        run: npm run test
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npx playwright install --with-deps chromium
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 15
      - name: Check pg_dump version
        run: pg_dump --version
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          cache-dependency-path: server/pom.xml
      - working-directory: client
        run: npm ci
      - working-directory: client
        run: npm run build
      - working-directory: server
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
